default:
  server:
    port: 3000
  database:
    host: "localhost"
    port: 27017
  cache:
    dir: "./dir"
development:
  database:
    db: "dev_db"
  cache:
    dir: "dinamic"
test:
  database:
    db: "test_db"
production:
  server:
    port: 8000
  database:
    db: "prod_db"
    user: "dbuser"
    password: "pass"
  cache:
    dir: "static"
